# Generated by Django 5.1.7 on 2025-03-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(choices=[('Council of Church', 'Council of Church'), ('Youth Council', 'Youth Council'), ("Y's Men", "Y's Men"), ('Central Club', 'Central Club')], max_length=64),
        ),
    ]
