# Generated by Django 5.1.7 on 2025-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_idcard_first_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='expired',
            field=models.BooleanField(default=True),
        ),
    ]
