# Generated by Django 5.1.7 on 2025-03-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_idcard_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profiles/'),
        ),
    ]
