# Generated by Django 5.1.7 on 2025-03-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_idcard_signature_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
