# Generated by Django 5.1.7 on 2025-07-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_user_academic_qualification_user_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="membership_category",
            field=models.CharField(
                choices=[
                    ("Full Membership", "Full Membership"),
                    ("Associate Membership", "Associate Membership"),
                    ("Honorary Membership", "Honorary Membership"),
                    ("Student Membership", "Student Membership"),
                ],
                default="Full Membership",
                max_length=50,
            ),
        ),
    ]
