# Generated by Django 5.1.7 on 2025-07-27 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_userrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
