# Generated by Django 5.1.7 on 2025-07-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_alter_userrequest_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrequest",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
