# Generated by Django 4.2 on 2025-10-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_userrequest_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrequest",
            name="age",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="church_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="citizen",
            field=models.CharField(default="Nigerian", max_length=20),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="club",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="home_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="lga",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="marital_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="next_of_kin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="occupation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="office_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="profession",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="referral_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="referral_source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="referred_by",
            field=models.CharField(default="no", max_length=10),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="religion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="valid_id_file",
            field=models.ImageField(blank=True, null=True, upload_to="request_photos/"),
        ),
        migrations.AlterField(
            model_name="userrequest",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userrequest",
            name="valid_id_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
