# Generated by Django 4.2 on 2025-10-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_userrequest_age_userrequest_church_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrequest",
            name="valid_id_type",
            field=models.CharField(
                choices=[
                    ("national_id", "National Identity Number (NIN)"),
                    ("drivers_license", "Driver's License"),
                    ("voters_card", "Voter's Card"),
                    ("international_passport", "International Passport"),
                    ("bvn", "Bank Verification Number (BVN)"),
                ],
                max_length=50,
            ),
        ),
    ]
