# Generated by Django 5.1.7 on 2025-10-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_alter_userrequest_valid_id_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrequest",
            name="valid_id_type",
        ),
    ]
