# Generated by Django 4.2 on 2025-10-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_remove_userrequest_valid_id_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="academic_qualification",
        ),
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="church",
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="declaration_accepted",
        ),
        migrations.RemoveField(
            model_name="user",
            name="denomination",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="home_address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="marital_status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="membership_category",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="user",
            name="next_of_kin_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="next_of_kin_phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="office_address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="other_names",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profession",
        ),
        migrations.RemoveField(
            model_name="user",
            name="referrer_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="religion",
        ),
        migrations.RemoveField(
            model_name="user",
            name="state_of_origin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="user",
            name="was_referred",
        ),
        migrations.RemoveField(
            model_name="user",
            name="youth_council_group",
        ),
        migrations.AddField(
            model_name="user",
            name="user_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_user",
                to="account.userrequest",
            ),
        ),
    ]
