# Generated by Django 5.1.7 on 2025-11-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_userrequest_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="membership_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("full", "Full Member"),
                    ("ordinary", "Ordinary Member"),
                    ("honorary", "Honorary Member"),
                    ("life", "Life Member"),
                ],
                default="full",
                max_length=20,
            ),
        ),
    ]
