# Generated by Django 5.1.7 on 2025-08-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("Announcements", "Announcements"),
                    ("Events", "Events"),
                    ("Prayer Requests", "Prayer Requests"),
                    ("Ministries", "Ministries"),
                    ("Sermons", "Sermons"),
                ],
                default="Announcements",
                max_length=20,
            ),
        ),
    ]
