# Generated by Django 5.1.7 on 2025-11-08 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("principal_officer", "Principal Officer"),
                            ("management_staff", "Management Staff"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
